### ISSUE TITLE
Can i host it on glitch?

### ISSUE THREAD

**Issue by Anonymyous678** [shukriadams/discord-giveawaybot#25]
Pls send me link to glitch project i will remix it and host

**Comment by shukriadams** [comment]
Currently don't have an active Glitch project for the bot, you can set it up easily enough using the instructions in readme, just specify this repo as the project source, and update settings.json with your API key etc. The bot appears an is reactive in Discord, but Glitch puts it to sleep after a few minutes. (see  https://github.com/shukriadams/discord-giveawaybot/issues/23)

**Comment by shukriadams** [comment]
Closing this as I don't think this will go any further, but feel free to reply further.
