### ISSUE TITLE
Unable to create giveaway with sub links (steam packs)

### ISSUE THREAD

**Issue by Skyrid3r** [shukriadams/discord-giveawaybot#8]
Example:

https://store.steampowered.com/sub/11652/

complete pack, but unable to use it in a giveaway.

Error : Game price could not be read from the link you provided, you will need to provide the game's price with --price or -p. Price should be digits only, egs --price 10  or --p 299.

Would have to include the price manually.

**Comment by shukriadams** [comment]
This is unfortunately a result of steam's API not providing prices for non-standard titles, bundles, etc. No war around it I'm afraid.
